language: cpp
os: linux
dist: focal
compiler:
  - clang
  - gcc
script:
  - cd lexilla/scripts
  - ./RunTest.sh
jobs:
  include:
    #- os: osx
      #osx_image: xcode12
      #before_script:
        #- cd lexilla/scripts
        #- python3 HFacer.py
        #- python3 LexillaGen.py
      #script:
        #- cd lexilla/src/Lexilla
        #- xcodebuild -project Lexilla.xcodeproj
        #- cd ..
        #- CLANG=1 make clean && make
        #- cd ../test
        #- CLANG=1 make && make test
    - os: windows
      install:
        - choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      script:
        - cd lexilla/scripts
        - CI=1 ./RunTest.bat
